- name: Run installer script
  become: true
  shell: INSTALL_K3S_SKIP_DOWNLOAD=true /usr/local/bin/k3s-install

- name: Get k3s token
  become: true
  shell: cat /var/lib/rancher/k3s/server/token
  register: k3s_token

